# Features Engineering

Dans cette section, nous allons effectuer l'ingénierie des caractéristiques sur notre dataset. Cette étape est cruciale pour transformer et créer de nouvelles variables qui pourront améliorer les performances de nos modèles. Nous allons créer des features pertinentes, normaliser les données si nécessaire, et préparer notre dataset pour la phase de modélisation.

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

data = pd.read_csv('../Merged_data/achats_merged.csv', sep=",")
data.head()

,id_achat,date_achat,id_produit,quantité,id_fournisseur,prix_unitaire,délai_livraison_jours,nom_fournisseur,ville,pays,fiabilité,délai_moyen_jours
0,PO000001,22/03/2024,P00627,150,S029,129.62,14,Fontaine Lopes S.A.,Helsinki,Finlande,0.54,6
1,PO000002,12/06/2024,P00469,50,S028,110.81,8,Delattre Blot S.A.,Berlin,Allemagne,0.74,8
2,PO000003,19/01/2024,P00849,75,S001,140.58,8,Lecomte et Fils,Zurich,Suisse,0.84,10
3,PO000004,20/11/2024,P00484,500,S028,120.77,9,Delattre Blot S.A.,Berlin,Allemagne,0.74,8
4,PO000005,07/06/2024,P00196,50,S025,256.05,13,Techer SA,Varsovie,Pologne,0.92,12

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_achat               10000 non-null  object
 1   date_achat             10000 non-null  object
 2   id_produit             10000 non-null  object
 3   quantité               10000 non-null  int64
 4   id_fournisseur         10000 non-null  object
 5   prix_unitaire          10000 non-null  float64
 6   délai_livraison_jours  10000 non-null  int64
 7   nom_fournisseur        10000 non-null  object
 8   ville                  10000 non-null  object
 9   pays                   10000 non-null  object
 10  fiabilité              10000 non-null  float64
 11  délai_moyen_jours      10000 non-null  int64
dtypes: float64(2), int64(3), object(7)
memory usage: 937.6+ KB

In [5]:
data['cout_total'] = data['quantité'] * data['prix_unitaire']
data.head()

,id_achat,date_achat,id_produit,quantité,id_fournisseur,prix_unitaire,délai_livraison_jours,nom_fournisseur,ville,pays,fiabilité,délai_moyen_jours,cout_total
0,PO000001,22/03/2024,P00627,150,S029,129.62,14,Fontaine Lopes S.A.,Helsinki,Finlande,0.54,6,19443.0
1,PO000002,12/06/2024,P00469,50,S028,110.81,8,Delattre Blot S.A.,Berlin,Allemagne,0.74,8,5540.5
2,PO000003,19/01/2024,P00849,75,S001,140.58,8,Lecomte et Fils,Zurich,Suisse,0.84,10,10543.5
3,PO000004,20/11/2024,P00484,500,S028,120.77,9,Delattre Blot S.A.,Berlin,Allemagne,0.74,8,60385.0
4,PO000005,07/06/2024,P00196,50,S025,256.05,13,Techer SA,Varsovie,Pologne,0.92,12,12802.5

In [6]:
data['date_livraison_estimee'] = pd.to_datetime(data['date_livraison_estimee'], format='%d/%m/%Y')

KeyError: 'date_livraison_estimee'